-- Chat Ativa - estrutura inicial para Supabase/Postgres.
-- O aplicativo usa autenticação própria no backend. Por isso, todas as
-- tabelas ficam protegidas por RLS sem políticas públicas; apenas o backend
-- com credencial de servidor poderá acessar os dados.

create table public.tenants (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null,
  active integer not null default 1 check (active in (0, 1)),
  created_at text not null default (timezone('utc', now())::text),
  updated_at text not null default (timezone('utc', now())::text)
);
create unique index tenants_slug_nocase on public.tenants (lower(slug));

create table public.global_settings (
  key text primary key,
  value text not null
);

create table public.settings (
  tenant_id bigint not null default 1 references public.tenants(id) on delete cascade,
  key text not null,
  value text not null,
  primary key (tenant_id, key)
);

create table public.contacts (
  tenant_id bigint not null default 1 references public.tenants(id) on delete cascade,
  jid text not null,
  name text,
  whatsapp_name_raw text,
  transport_jid text,
  bot_paused integer not null default 0 check (bot_paused in (0, 1)),
  service_status text not null default 'open' check (service_status in ('open', 'resolved')),
  assigned_user_id bigint,
  current_cycle_id bigint,
  last_unanswered_alert_message_id bigint,
  last_message_at text,
  last_read_message_id bigint not null default 0,
  synced_at text,
  created_at text not null default (timezone('utc', now())::text),
  primary key (tenant_id, jid)
);

create table public.customers (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null default 1 references public.tenants(id) on delete cascade,
  first_name text not null,
  last_name text not null,
  phone text not null,
  extra_data text not null default '{}',
  created_at text not null default (timezone('utc', now())::text),
  updated_at text not null default (timezone('utc', now())::text),
  unique (tenant_id, phone)
);
create index idx_customers_name on public.customers (tenant_id, first_name, last_name);

create table public.messages (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null default 1 references public.tenants(id) on delete cascade,
  jid text not null,
  direction text not null check (direction in ('in', 'out')),
  text text not null,
  source text not null default 'user',
  message_type text not null default 'text',
  mime_type text,
  file_name text,
  media_path text,
  file_size bigint,
  duration_seconds integer,
  is_voice_note integer not null default 0 check (is_voice_note in (0, 1)),
  author_user_id bigint,
  author_name text,
  cycle_id bigint,
  external_id text,
  external_timestamp text,
  created_at text not null default (timezone('utc', now())::text)
);
create index idx_messages_jid on public.messages (tenant_id, jid, id);
create unique index idx_messages_external_id
  on public.messages (tenant_id, external_id)
  where external_id is not null;

create table public.canned_responses (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null default 1 references public.tenants(id) on delete cascade,
  name text not null,
  triggers text not null,
  match_type text not null default 'contains',
  response text not null,
  enabled integer not null default 1 check (enabled in (0, 1)),
  priority integer not null default 0
);

create table public.rules (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null default 1 references public.tenants(id) on delete cascade,
  name text not null,
  pattern text not null,
  match_type text not null default 'contains',
  action text not null default 'reply',
  response text,
  enabled integer not null default 1 check (enabled in (0, 1)),
  priority integer not null default 0
);

create table public.knowledge (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null default 1 references public.tenants(id) on delete cascade,
  question text not null,
  answer text not null,
  source text not null default 'manual',
  status text not null default 'approved',
  usage_count integer not null default 0,
  confidence double precision not null default 0.8,
  created_at text not null default (timezone('utc', now())::text)
);

create table public.smart_notes (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null default 1 references public.tenants(id) on delete cascade,
  jid text not null,
  category text not null,
  title text not null,
  content text not null,
  status text not null default 'open' check (status in ('open', 'done')),
  created_at text not null default (timezone('utc', now())::text),
  updated_at text not null default (timezone('utc', now())::text)
);
create index idx_smart_notes_status
  on public.smart_notes (tenant_id, status, updated_at desc);

create table public.smart_note_messages (
  note_id bigint not null references public.smart_notes(id) on delete cascade,
  message_id bigint not null unique,
  primary key (note_id, message_id)
);

create table public.users (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null default 1 references public.tenants(id) on delete cascade,
  username text not null,
  display_name text not null,
  password_hash text not null,
  role text not null default 'attendant'
    check (role in ('super_admin', 'admin', 'attendant')),
  active integer not null default 1 check (active in (0, 1)),
  created_at text not null default (timezone('utc', now())::text),
  updated_at text not null default (timezone('utc', now())::text)
);
create unique index users_username_nocase on public.users (lower(username));

create table public.conversation_cycles (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null default 1 references public.tenants(id) on delete cascade,
  jid text not null,
  status text not null default 'open' check (status in ('open', 'resolved')),
  assigned_user_id bigint references public.users(id) on delete set null,
  opened_by bigint references public.users(id) on delete set null,
  resolved_by bigint references public.users(id) on delete set null,
  started_at text not null default (timezone('utc', now())::text),
  resolved_at text
);
create index idx_conversation_cycles_jid
  on public.conversation_cycles (tenant_id, jid, id desc);

create table public.internal_notes (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null default 1 references public.tenants(id) on delete cascade,
  jid text not null,
  author_id bigint references public.users(id) on delete set null,
  author_name text not null,
  text text not null,
  created_at text not null default (timezone('utc', now())::text),
  updated_at text not null default (timezone('utc', now())::text)
);
create index idx_internal_notes_jid
  on public.internal_notes (tenant_id, jid, id desc);

create table public.internal_messages (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null default 1 references public.tenants(id) on delete cascade,
  sender_id bigint references public.users(id) on delete set null,
  sender_name text not null,
  recipient_id bigint not null references public.users(id) on delete cascade,
  text text not null default '',
  message_type text not null default 'text',
  mime_type text,
  file_name text,
  media_path text,
  file_size bigint,
  duration_seconds integer,
  is_voice_note integer not null default 0 check (is_voice_note in (0, 1)),
  created_at text not null default (timezone('utc', now())::text)
);
create index idx_internal_messages_thread
  on public.internal_messages (tenant_id, sender_id, recipient_id, id);

create table public.history_imports (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null default 1 references public.tenants(id) on delete cascade,
  jid text not null,
  imported_by bigint references public.users(id) on delete set null,
  file_name text not null,
  messages_imported integer not null default 0,
  created_at text not null default (timezone('utc', now())::text)
);

create table public.weekly_availability (
  tenant_id bigint not null default 1 references public.tenants(id) on delete cascade,
  weekday integer not null check (weekday between 0 and 6),
  enabled integer not null default 1 check (enabled in (0, 1)),
  start_time text not null default '09:00',
  end_time text not null default '18:00',
  slot_minutes integer not null default 60,
  primary key (tenant_id, weekday)
);

create table public.calendar_exceptions (
  tenant_id bigint not null default 1 references public.tenants(id) on delete cascade,
  date text not null,
  is_open integer not null default 0 check (is_open in (0, 1)),
  start_time text,
  end_time text,
  note text,
  primary key (tenant_id, date)
);

create table public.appointments (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null default 1 references public.tenants(id) on delete cascade,
  jid text,
  customer_name text not null,
  title text not null,
  start_at text not null,
  end_at text not null,
  status text not null default 'scheduled'
    check (status in ('scheduled', 'completed', 'cancelled')),
  notes text,
  source text not null default 'manual' check (source in ('manual', 'ai')),
  created_by bigint references public.users(id) on delete set null,
  created_at text not null default (timezone('utc', now())::text),
  updated_at text not null default (timezone('utc', now())::text)
);
create index idx_appointments_start
  on public.appointments (tenant_id, start_at, status);
create index idx_appointments_jid
  on public.appointments (tenant_id, jid, start_at desc);

create table public.external_requests (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null default 1 references public.tenants(id) on delete cascade,
  source_jid text not null,
  target_jid text not null,
  request_message_id bigint not null,
  request_text text not null,
  status text not null default 'pending'
    check (status in ('pending', 'approved', 'declined')),
  response_message_id bigint,
  response_text text,
  created_at text not null default (timezone('utc', now())::text),
  resolved_at text
);
create index idx_external_requests_target
  on public.external_requests (tenant_id, target_jid, status, id);
create index idx_external_requests_source
  on public.external_requests (tenant_id, source_jid, status, id desc);

create table public.appointment_notifications (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null default 1 references public.tenants(id) on delete cascade,
  appointment_id bigint not null,
  jid text not null,
  message text not null,
  status text not null default 'pending' check (status in ('pending', 'sent')),
  last_error text,
  created_at text not null default (timezone('utc', now())::text),
  sent_at text
);
create index idx_appointment_notifications_pending
  on public.appointment_notifications (tenant_id, status, id);

create table public.api_usage (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null default 1 references public.tenants(id) on delete cascade,
  provider text not null default 'xai',
  model text not null,
  purpose text not null default 'chat_reply',
  prompt_tokens integer not null default 0,
  cached_tokens integer not null default 0,
  completion_tokens integer not null default 0,
  reasoning_tokens integer not null default 0,
  total_tokens integer not null default 0,
  cost_usd double precision not null default 0,
  estimated integer not null default 0 check (estimated in (0, 1)),
  response_id text,
  created_at text not null default (timezone('utc', now())::text)
);
create index idx_api_usage_created
  on public.api_usage (tenant_id, created_at desc);
create index idx_api_usage_model
  on public.api_usage (tenant_id, model, created_at desc);

insert into public.tenants (id, name, slug)
values (1, 'Empresa principal', 'empresa-principal');

insert into storage.buckets (id, name, public, file_size_limit)
values ('chat-media', 'chat-media', false, 26214400)
on conflict (id) do nothing;

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'tenants', 'global_settings', 'settings', 'contacts', 'customers',
    'messages', 'canned_responses', 'rules', 'knowledge', 'smart_notes',
    'smart_note_messages', 'users', 'conversation_cycles', 'internal_notes',
    'internal_messages', 'history_imports', 'weekly_availability',
    'calendar_exceptions', 'appointments', 'external_requests',
    'appointment_notifications', 'api_usage'
  ]
  loop
    execute format('alter table public.%I enable row level security', table_name);
  end loop;
end
$$;
